CREATE USER "COFORM" IDENTIFIED BY "COFORM" DEFAULT TABLESPACE "COFORM_DAT_N01" TEMPORARY TABLESPACE "TEMP";

GRANT "CONNECT" TO "COFORM";

GRANT "RESOURCE" TO "COFORM";

GRANT SELECT ANY DICTIONARY TO "COFORM";

GRANT UNLIMITED TABLESPACE TO "COFORM";

GRANT CREATE PROCEDURE TO "COFORM";

GRANT EXECUTE ANY PROCEDURE TO "COFORM";

ALTER USER "COFORM" QUOTA UNLIMITED ON "COFORM_DAT_N01" ;
ALTER USER "COFORM" QUOTA UNLIMITED ON "COFORM_IDX_N01" ;

exit;
